name: pga-frontend-prod
region: ams
static_sites:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: SCF-Public-Goods-Maintenance/pg-atlas-frontend
    name: pg-atlas-frontend
    source_dir: /
features:
  - buildpack-stack=ubuntu-22
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: pg-atlas-frontend
    match:
      authority:
        exact: ""
      path:
        prefix: /
